### ISSUE TITLE
Crache on miui

### ISSUE THREAD

**Issue by Norfolk2** [cedricp/ecutweaker#6]
App crache on redmi note 10 5G eather on miui 12.5 or 14.0.6 at startup, this occure when according file Access authorization

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException: Attempt to read from field 'long org.quark.dr.ecu.ZipFileSystem$CustomZipEntry.pos' on a null object reference
	at org.quark.dr.ecu.ZipFileSystem.getZipFileAsBytes(ZipFileSystem.java:134)
	at org.quark.dr.ecu.ZipFileSystem.getZipFile(ZipFileSystem.java:124)
	at org.quark.dr.ecu.EcuDatabase.loadDatabase(EcuDatabase.java:342)
	at org.quark.dr.canapp.MainActivity$LoadDbTask.doInBackground(MainActivity.java:874)
	at org.quark.dr.canapp.MainActivity$LoadDbTask.doInBackground(MainActivity.java:865)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by Norfolk2** [comment]
Solved, problème was corrupted ecu bases
